// Auto-generated by SignalR.Proximity.TS.ContractGenerator
// Do not edit manually.

export interface ISchoolContract {
    Send(message: string, from: string): void;
}

export const schoolContractSignatures = {
    Send: "Void Send(string, string)"
};

export const schoolContractPath = "sample.signalr.proximity.toaster.ischoolcontract";
