// Auto-generated by SignalR.Proximity.TS.ContractGenerator
// Do not edit manually.

export class WorkflowStepProgress {
    public Key!: string;
    public Name!: string;
    public Description!: string;
    public Status!: string;
}

export class WorkflowProgess {
    public Key!: string;
    public Name!: string;
    public Description!: string;
    public Status!: string;
    public Steps!: WorkflowStepProgress[];
}

export interface ISchoolContract {
    Send(message: string, from: string): void;
    OnWorkflowProgess(progresss: WorkflowProgess): void;
}

export const schoolContractSignatures = {
    Send: "Void Send(System.String, System.String)",
    OnWorkflowProgess: "Void OnWorkflowProgess(Sample.SignalR.Proximity.Toaster.WorkflowProgess)"
};

export const schoolContractPath = "sample.signalr.proximity.toaster.ischoolcontract";
