// Auto-generated by SignalR.Proximity.TS.ContractGenerator
// Do not edit manually.

export class ToasterRequest {
    public CorrelationKey!: string | null;
    public Title!: string;
    public Message!: string;
    public FromUser!: string;
}

export interface IToastNotificationsContract {
    ShowInformation(request: ToasterRequest): void;
    ShowSuccess(request: ToasterRequest): void;
    ShowWarning(request: ToasterRequest): void;
    ShowError(request: ToasterRequest): void;
}

export const toastNotificationsContractSignatures = {
    ShowInformation: "Void ShowInformation(Sample.SignalR.Proximity.Toaster.ToasterRequest)",
    ShowSuccess: "Void ShowSuccess(Sample.SignalR.Proximity.Toaster.ToasterRequest)",
    ShowWarning: "Void ShowWarning(Sample.SignalR.Proximity.Toaster.ToasterRequest)",
    ShowError: "Void ShowError(Sample.SignalR.Proximity.Toaster.ToasterRequest)"
};

export const toastNotificationsContractPath = "sample.signalr.proximity.toaster.itoastnotificationscontract";
