name: "CI" 

on:
  push:
    branches: [master,vNext]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master,vNext]
  schedule:
    - cron: '45 9 * * 6'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
 
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        config-file: ./.github/codeql-config.yml

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
 